### PR TITLE
Removed shared pointer reference

### PR DESCRIPTION
**Pull request by WhySoBad**
Using this fix the plugin works again for `hyprland-git 0.41.1.r54.4a8b13ea-1`

### CODE REVIEW

**Comment by levnikmyskin** [comment]
Hi, code part looks good. I'll accept it and merge it once CI is fixed. If you can take care of that it'd be amazing, otherwise I'll commit to this branch (apparently `hyprutils` is missing from CI)

**Comment by WhySoBad** [comment]
I don't really understand the problem it's having. When I looked at your CI it seemed as if you were installing hyprutils?

**Comment by WhySoBad** [comment]
@levnikmyskin I was able to fix the CI by installing `hyprutils` in the setup step :)

**Review by levnikmyskin — APPROVED** [review]
Thank you as usual for your help :)

**Pull request merged**
