### PR TITLE
Fixed hyprpm implementation

### PR DESCRIPTION
**Pull request by guusbotman**
Hello,

I tried using your hyprpm branch to add this plugin using the hyprpm, but it was unable to compile it. I fixed the error codes and got it working for my system using the "hyprpm add https://github.com/guusbotman/hyprland-virtual-desktops" command.

Hope you can use it, kind regards

### CODE REVIEW

**Comment by levnikmyskin** [comment]
Hey! Thank you so much for your work. I'll give a proper review + testing tomorrow. From a first look, why the wlr unstable thing?

**Comment by levnikmyskin** [comment]
I'll merge your stuff into my branch, and then I'll take it from there :) thank you very much again

**Comment by guusbotman** [comment]
Hello!

No problem at all! I use your virtual desktop plugin every day and I'm very
fond of it. I'm definitely not a top notch programmer as yourself.
I just followed the hyprpm guide to install external plugins, and noticed
the plugin would not compile through it. I used the hyprpm -v option to
give me a more detailed error and tried to fix the errors one by one.
The compiler complained about the missing of wlr unstable, so I added it
where it would give me errors.

Hope to help you this way,
Thanks for your great work

Guus Botman

Op za 13 jan 2024 om 11:41 schreef Alessio Molinari <
***@***.***>:

**Comment by levnikmyskin** [comment]
Thank you very much for your kind words, I do appreciate them, even though I definitely do not consider myself a good programmer in C++. But I'm super glad that you find my plugin useful :)

**Pull request merged**
